apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: nextcloud
  labels:
    environment: extern
    app: nextcloud
spec:
  selector:
    app: nextcloud
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 8088
      name: web