apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn-conf
  #namespace: turn
  namespace: cert-manager
data:
  coturn.conf: |
    log-file=stdout
    relay-ip=NODE_IP #TODO
    listening-port=5349
    min-port=49160
    max-port=49200
    use-auth-secret
    static-auth-secret=passwd #TODO
    realm=turn.example.tld:5349
    no-cli
    cert=/var/run/secret/tls.crt
    pkey=/var/run/secret/tls.key