apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-deploy
  namespace: db
  labels:
    environment: intern
    app: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      volumes:
        - name: vol
          nfs:
            server: NODE_IP #TODO
            path: /mnt/data/elastic
      containers:
        - name: elastic
          image: elasticsearch:7.10.1
          volumeMounts:
            - name: vol
              mountPath: /usr/share/elasticsearch/data
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
