apiVersion: v1
kind: Service
metadata:
  name: elastic-service
  namespace: db
  labels:
    environment: intern
    app: elastic
spec:
  externalIPs:
    - NODE_IP #TODO
  externalTrafficPolicy: Cluster
  ports:
    - targetPort: 9200
      port: 9200
      nodePort: 31200
  selector:
    app: elastic
  type: NodePort