apiVersion: v1
kind: Service
metadata:
  name: syncthing-service
  namespace: syncthing
  labels:
    environment: intern
    app: syncthing
spec:
  selector:
    app: syncthing
  type: ClusterIP
  ports:
    - targetPort: 8384
      port: 8384