apiVersion: v1
kind: Service
metadata:
  name: synapse-admin-service
  namespace: matrix
  labels:
    environment: intern
    app: synapse-admin
spec:
  selector:
    app: synapse-admin
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 8013