apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: db
  labels:
    environment: intern
    app: postgres
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
