apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: mon
  labels:
    environment: mon
    app: prometheus
  annotations:
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: prometheus
  type: ClusterIP
  ports:
    - targetPort: 9090
      port: 9099