apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
  namespace: jitsi
spec:
  ports:
  - name: "http"
    port: 8012
    targetPort: 80
  - name: "https"
    port: 4412
    targetPort: 443
  selector:
    k8s-app: jitsi
