apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-tld-cert
  namespace: cert-manager
spec:
  renewBefore: 360h #15d
  secretName: example-tld-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - grafana.example.tld
    - matrix.example.tld
    - shome.example.tld
    - cloud.example.tld
    - plex.example.tld
    - jellyfin.example.tld
    - turn.example.tld