apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'mail@example.tld' #TODO
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
    # - dns01:
    #     webhook:
    #       groupName: 'acme.example.tld' #TODO
    #       solverName: ovh
    #       config:
    #         endpoint: ovh-eu
    #         applicationKey: '' #TODO
    #         applicationSecretRef:
    #           key: applicationSecret
    #           name: ovh-credentials
    #         consumerKey: '' #TODO