apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: db
  labels:
    environment: intern
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: vol
          nfs:
            server: NODE_IP #TODO
            path: /mnt/data/sql
        - name: backup
          nfs:
            server: NODE_IP #TODO
            path: /mnt/data/db-backup/mysql
      containers:
        - name: mysql
          image: mysql:8.0
          volumeMounts:
            - name: vol
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-passwd
        - name: mysql-backup
          image: fradelg/mysql-cron-backup
          volumeMounts:
            - name: backup
              mountPath: /backup
          env:
            - name: MYSQL_HOST
              value: "mysql-service.db"
            - name: MYSQL_USER
              value: "root"
            - name: CRON_TIME
              value: "0 1 * * *"
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-passwd