apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: db
  labels:
    environment: intern
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306