apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-deploy
  namespace: mon
  labels:
    environment: mon
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager
      containers:
        - name: alertmanager
          image: prom/alertmanager
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
          ports:
            - containerPort: 9090