apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: mon
  labels:
    environment: mon
    app: prometheus
spec:
  selector:
    app: prometheus
  type: ClusterIP
  ports:
    - targetPort: 9090
      port: 9099