apiVersion: v1
kind: Service
metadata:
  name: influx-service
  namespace: db
  labels:
    environment: intern
    app: influx
spec:
  externalIPs:
    - NODE_IP #TODO
  externalTrafficPolicy: Cluster
  ports:
    - targetPort: 8086
      port: 8086
      nodePort: 31086
  selector:
    app: influx
  type: NodePort
