apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  namespace: mon
  labels:
    environment: mon
    app: node-exporter
spec:
  selector:
    app: node-exporter
  type: ClusterIP
  ports:
    - targetPort: 9100
      port: 9100