apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    environment: intern
    app: db
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: netview
#  labels:
#    environment: extern
#    app: grafana
---
apiVersion: v1
kind: Namespace
metadata:
  name: adguardhome
  labels:
    environment: intern
    app: adguardhome
---
apiVersion: v1
kind: Namespace
metadata:
  name: unifi
  labels:
    environment: intern
    app: unifi
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    environment: extern
    app: grafana
---
apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
  labels:
    environment: extern
    app: homeassistant
---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
  labels:
    environment: extern
    app: nextcloud
---
apiVersion: v1
kind: Namespace
metadata:
  name: plex
  labels:
    environment: extern
    app: plex
---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
  labels:
    environment: extern
    app: jellyfin
---
apiVersion: v1
kind: Namespace
metadata:
  name: matrix
  labels:
    environment: extern
    app: matrix
---
apiVersion: v1
kind: Namespace
metadata:
  name: mon
  labels:
    environment: mon
    app: mon
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    environment: extern
    app: traefik
---
apiVersion: v1
kind: Namespace
metadata:
  name: teamspeak
  labels:
    environment: extern
    app: teamspeak
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
  labels:
    environment: extern
    app: kubernetes-dashboard