apiVersion: v1
kind: Service
metadata:
  name: delegation-service
  namespace: matrix
  labels:
    environment: extern
    app: matrix
spec:
  selector:
    app: delegation-nginx
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 8449
      name: web-ui