apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-mysql
  - 02-postgres
# - 03-maria
  - 04-influxdb
# - 05-elastic

secretGenerator:
  - name: db-passwd
    namespace: db
    literals:
      - password=passwd #TODO