apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

secretGenerator:
  - name: plex-token
    namespace: plex
    literals:
      - claim=claim- #TODO
